include $(APPDIR)/Make.defs

# Nombre del programa
PROGNAME = lab1_server
PRIORITY = SCHED_PRIORITY_DEFAULT
STACKSIZE = 2048
MODULE = $(CONFIG_EXAMPLES_HELLO_NUTTX)

# Archivos fuente
MAINSRC = lab1_server.c

include $(APPDIR)/Application.mk
